name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: secbank
          POSTGRES_PASSWORD: secbank_pass
          POSTGRES_DB: secbank_test
        options: >-
          --health-cmd pg_isready -U secbank
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci
      - run: npx prisma generate
      - run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://secbank:secbank_pass@localhost:5432/secbank_test?schema=public

      - run: npm run typecheck
      - run: npm test
        env:
          DATABASE_URL: postgresql://secbank:secbank_pass@localhost:5432/secbank_test?schema=public
          JWT_SECRET: ci-secret-that-is-at-least-thirty-two-characters!!
